version: '3.9'

services:
  db:
    image: postgres
    container_name: postgresDB
    restart: always
    environment:
      POSTGRES_DB: chessappdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - database-volume:/var/lib/postgresql/data
    networks:
      - chess_database

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - chess_database

volumes:
  database-volume:


networks:
  chess_database:
